edu_iitians/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from quiz import views as quiz_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls",namespace='home_view')),
    url('september/', include('quiz.urls')),
    url(r'^quiz2/', include('quiz_2.urls')),

 
]

# from django.conf import settings
# from django.conf.urls.static import static



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = quiz_views.error_404
handler500 = quiz_views.error_500

home/urls.py
from django.urls import path
from .views import IndexView,registration,contact,Exercise_home

app_name = 'home'

urlpatterns = [    
    # path('',IndexView.as_view(), name='home1'),
    # path('exercise/',Exercise_home),
    path('',Exercise_home),
    path('register/',registration,name='register1'),
    
    path('contact/',contact,name='contact')
]

quiz/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'quiz'

urlpatterns = [
   url(r'^$', views.home, name='home'),
    url(r'^user-home$', views.user_home, name='user_home'),
    url(r'^play/$', views.play, name='play'),
    url(r'^leaderboard/$', views.leaderboard, name='leaderboard'),
    url(r'^submission-result/(?P<attempted_question_pk>\d+)/', views.submission_result, name='submission_result'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/', views.register, name='register'),
    

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}  JEE Marathon Quizzes  {% endblock title %}</title>

        <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">

  <!--   <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block css %}
    {% endblock css %} -->
<style>

section.gallery .mix {
    padding: 0;
    max-height: 300px;
    overflow: hidden;
  }</style>

  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R5Z6JTPHPR"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-R5Z6JTPHPR');
</script>
</head>

<body class="bg-white">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <h1><a href="/" class="navbar-brand">
            <strong>EduIITians</strong></a></h1>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse justify-content-end " id="navbar">
                {% if not request.user.is_active %}
                <a href="/" class="btn btn-info mt-1 mx-1">Exercises</a>
                <a href="{% url 'quiz:login' %}" class="btn btn-success mt-1 ml-2"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a>
                {% else %}
                <h6 class="text-white mt-2 mr-2">Welcome, {{ request.user.username }}</h6>
                <h6 class="text-light mt-2 mr-2">|</h6>
                <h6 class="text-white mt-2 mr-2"><a href="/" class="text-info">All Exercises</a></h6>
                
                
                <a href="{% url 'quiz:logout' %}" class="btn btn-danger mt-1 ml-4">Log Out <i class="fa fa-sign-out" aria-hidden="true"></i></a>
                {% endif %}
            </div>
        </div>

    </nav>

    {% block content %}
    {% endblock content %}
    <footer class="bg-light text-muted py-0">
        <div class="container py-4">
            <ul class="list-inline mb-0 text-center">
                <li class="list-inline-item">&copy; An Initiative by EduIITians</li>
                <li class="list-inline-item">All rights reserved.</li>
            </ul>
        </div>
    </footer>
    <!-- jQuery first, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/12.1.5/js/smooth-scroll.min.js" integrity="sha256-MMt0/21G3z0Zg4ET1kI3HC9npItDowkitRDVr0FhCxA=" crossorigin="anonymous"></script>

    <!-- <script src="{% static 'js/main.js' %}"></script>
    {% block js %}{% endblock js %} -->
</body>
</html>

templates/contact.html
{% extends 'index.html' %}
{% block content %}
<!-- CONTENT HOLDER -->
<div class="htheme_content_holder">

	<!-- SET HEADER IF ON IS NOT SELECTED -->
	
	<!-- ROW -->
	<div class="htheme_row htheme_padding_bottom">
		<div class="htheme_container">
			<div class="htheme_inner_col">
				<!-- TITLE DEFAULT -->
				<div class="htheme_title_container" data-title-type="default">
					<div class="htheme_title">
						<h1>
															HEY! WE’D LOVE TO MEET YOU													</h1>
					</div>
											<div class="htheme_title_devider_holder  htheme_diagonal"></div>
														</div>
			</div>
		</div>
	</div>
	<!-- ROW -->

									<!-- ROW -->
		<div class="htheme_row_margin_top_bottom htheme_vc_row_contained">
		<!-- ROW -->
		<div class="htheme_row">
			<div class="htheme_container">
				<div class="htheme_contact_details_holder">
					<div class="htheme_contact_details_item">
						<div class="htheme_col_12 htheme_contact_map">
							<div class="htheme_inner_col">
								<div class="htheme_map_holder" id="htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ROW -->
				<script type="text/javascript">

			function htheme_initMap() {

				//CREATE MAP
				var map_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7 = new google.maps.Map(document.getElementById('htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7'), {
					center: {lat:24.179331, lng: 72.426682},
					scrollwheel: true,
					zoom: 10				});

				
				var styles_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7 = [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#000000"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":21}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":16}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":19}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":17}]}];

				map_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7.setOptions({styles: styles_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7});

				//ADD MARKERS
				
				
					
						
							
							//WINDOW INFO
							var contentString0 = '<div id="content">'+

								'<h4 class="htheme_map_heading">'+
									''+
								'</h4>'+
								'<div class="htheme_default_content">'+
									'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla interdum ex non porta vestibulum.'+
								'</div>'+
								'</div>';

							var infowindow0 = new google.maps.InfoWindow({
								content: contentString0							});

							//MARKER
							var marker0 = new google.maps.Marker({
								map: map_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7,
								position: {lat: 24.179331, lng: 72.426682},
								icon: 'https://invogue.heroplugins.com/wp-content/uploads/2016/05/marker_white.png'
							});
							var marker1 = new google.maps.Marker({
								map: map_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7,
								position: {lat: 20.179331, lng: 70.426682},
								icon: 'https://invogue.heroplugins.com/wp-content/uploads/2016/05/marker_white.png'
							});
							var marker2 = new google.maps.Marker({
								map: map_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7,
								position: {lat: 24.179331, lng: 71.426682},
								icon: 'https://invogue.heroplugins.com/wp-content/uploads/2016/05/marker_white.png'
							});

							//ADD LISTENERS
							marker0.addListener('click', function() {
								infowindow0.open(map_htheme_map_48f95096_7a2c_4fce_87dc_dcf52e0a51a7, marker0, marker1, marker2);
							});

							
						
									
			}
		</script>

		
		<div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"></div></div></div></div><div class="htheme_row_margin_top_bottom htheme_vc_row_contained"><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="vc_icon_element vc_icon_element-outer vc_custom_1487694246660 wpb_animate_when_almost_visible wpb_appear appear vc_icon_element-align-left">
	<div class="vc_icon_element-inner vc_icon_element-color-custom vc_icon_element-size-md vc_icon_element-style- vc_icon_element-background-color-grey">
		<span class="vc_icon_element-icon vc_li vc_li-bubble" style="color:#2b2b2b !important"></span></div>
</div>

	<div class="wpb_text_column wpb_content_element ">
		<div class="wpb_wrapper">
			<div class="htheme_inner_col htheme_default_content">
				<h2>SPEAK TO US</h2>
<p>Sales. fashion@fashion.com<br>
Deliveries. deliveries@fashion.com<br>
Phone. 0123 4567 0033<br>
Fax. 0123 4567 0066</p>

			</div>
		</div>
	</div>
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="vc_icon_element vc_icon_element-outer vc_custom_1487694209724 wpb_animate_when_almost_visible wpb_appear appear vc_icon_element-align-left">
	<div class="vc_icon_element-inner vc_icon_element-color-custom vc_icon_element-size-md vc_icon_element-style- vc_icon_element-background-color-grey">
		<span class="vc_icon_element-icon vc_li vc_li-location" style="color:#2b2b2b !important"></span></div>
</div>

	<div class="wpb_text_column wpb_content_element ">
		<div class="wpb_wrapper">
			<div class="htheme_inner_col htheme_default_content">
				<h2>FIND US HERE</h2>
<p>2001 West 115th Street<br>
Suite 2001<br>
New York<br>
NY 10010</p>

			</div>
		</div>
	</div>
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="vc_icon_element vc_icon_element-outer vc_custom_1487694259600 wpb_animate_when_almost_visible wpb_appear appear vc_icon_element-align-left">
	<div class="vc_icon_element-inner vc_icon_element-color-custom vc_icon_element-size-md vc_icon_element-style- vc_icon_element-background-color-grey">
		<span class="vc_icon_element-icon vc_li vc_li-shop" style="color:#2b2b2b !important"></span></div>
</div>

	<div class="wpb_text_column wpb_content_element ">
		<div class="wpb_wrapper">
			<div class="htheme_inner_col htheme_default_content">
				<h2>YES WE ARE OPEN</h2>
<p>Support is available 24/7<br>
Monday-Friday: 8am to 6pm<br>
Saturday: 10am to 2pm<br>
Sunday: Closed</p>

			</div>
		</div>
	</div>
</div></div></div></div><div class="htheme_row_margin_top_bottom htheme_vc_row_contained">		<!-- GREY LINE -->
		<div class="htheme_row">
						<div class="htheme_container">
				<div class="htheme_inner_col">
								<div class="htheme_grey_line_separator" style="background-color:#e2e2e2"></div>
							</div>
			</div>
					</div>
		<!-- GREY LINE -->
		<div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"></div></div></div></div><div class="htheme_row_margin_top htheme_vc_row_contained"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><!-- ROW --><div class="htheme_row"><div class="htheme_container"><div class="htheme_inner_col"><!-- TITLE DEFAULT --><div class="htheme_title_container" data-title-type="default"><div class="htheme_title"><h2>FEEL FREE TO DROP US AN EMAIL</h2></div></div></div></div></div><!-- ROW --></div></div></div></div><div class="htheme_row_padding_bottom htheme_row_margin_top_bottom htheme_vc_row_contained"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><!-- ROW -->
            <form id="htheme_contact_form_d12678a7_fe22_4c1d_b705_c3179d7b6a7b" class="htheme_contact_form" data-subject="Please let us know"><div class="htheme_row"><div class="htheme_container"><div class="htheme_inner_col"><div class="htheme_form_holder"><div class="htheme_col_6 htheme_form_field_item">
                <input type="text" name="first_name" id="user_name"><label for="user_name" class>First Name</label></div><div class="htheme_col_6 htheme_form_field_item">
                    <input type="text" name="last_name" id="user_last"><label for="user_last" class>Last Name</label></div><div class="htheme_col_6 htheme_form_field_item">
                    <input type="text" name="email" id="user_email"><label for="user_email" class>Email Address</label></div><div class="htheme_col_6 htheme_form_field_item">
                    <input type="text" name="message_type" id="user_message_type"><label for="user_message_type" class>Message Type</label></div><div class="htheme_col_12 htheme_form_field_item htheme_form_textarea_item">
                        <textarea name="message" id="user_message"></textarea><label for="user_message" class>Message</label></div><div class="htheme_form_status_message"></div><div class="htheme_btn_style_1" id="htheme_button_submit">Send</div></div></div></div></div></form><!-- ROW --></div></div></div></div><div class="htheme_row_margin_top htheme_vc_row_full_content_full_no_space"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><!-- ROW --><div class="htheme_row"><div class="htheme_instagram_holder"><div class="htheme_instagram_images"></div><a target="_blank" href="https://www.instagram.com//" class="htheme_pinterest_content" data-hover-type="hover_pinterest_block"><span class="htheme_h3_sub">Find us on instagram</span><h3>@invoguetheme</h3></a></div></div><!-- ROW --></div></div></div></div>
		<!-- ROW -->
				    
    <!-- COMMENTS -->
	    <!-- COMMENTS -->

</div>
<!-- CONTENT HOLDER -->
{% endblock %}

templates/exercise_home.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} JEE Marathon Quiz | List {% endblock title %}
{% block content %}
<div class="container">
    <h1 class="text-center my-4"><span class="badge badge-primary"><i class="fa fa-trophy" aria-hidden="true"></i> Live JEE Marathons <i class="fa fa-trophy" aria-hidden="true"></i></span></h1>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Marathon Name</th>                            
                <th>Leaderboard Link</th>
                <th>Upadted On</th>
            </tr>
        </thead>
        <tbody>
            {% for exercise in exercises %}
            <tr>
                <td>{{ forloop.counter }}</td>
                
                <td><a href="{{ exercise.exercise_link}}" class="href">{{ exercise.exercise_name }}</a></td>
                <td><a href="{{ exercise.leaderboard_link }}" class="href">Leaderboard Link</a></td> 
                <td>{{ exercise.updated_date }}</td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

templates/register.html
{% extends 'index.html' %}
{% block content %}

<div class="htheme_content_holder">

	<!-- SET HEADER IF ON IS NOT SELECTED -->
	
	<!-- ROW -->
	<div class="htheme_row htheme_padding_bottom">
		<div class="htheme_container">
			<div class="htheme_inner_col">
				<!-- TITLE DEFAULT -->
				<div class="htheme_title_container" data-title-type="default">
					{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}
					<div class="htheme_title">
						<h1>
															Register													</h1>
					</div>
														</div>
			</div>
		</div>
	</div>
	<!-- ROW -->

					<!-- ROW -->
		<div class="htheme_row">
			<div class="htheme_container">
				<div class="htheme_inner_col">
					<div class="woocommerce">
	
<form name="checkout" method="post" class="checkout woocommerce-checkout" action="." enctype="multipart/form-data" novalidate="novalidate">
	{% csrf_token %}
	
		
		<div class="col2-set" id="customer_details">
			<div class="col-1">
				<div class="woocommerce-billing-fields">
	
		<h3>Student details</h3>

	
	
	<div class="woocommerce-billing-fields__field-wrapper">
		<p class="form-row form-row-wide" id="billing_company_field" data-sort="30">
			<label for="name" class="">Student's Name</label>
			<input type="text" class="input-text " name="name" id="name" placeholder="" value="" autocomplete="organization"></p>
	
	<p class="form-row form-row-wide" id="billing_company_field" data-sort="30">
		<label for="father_name" class="">Father's Name</label>
		<input type="text" class="input-text " name="father_name" id="father_name" placeholder="" value="" autocomplete="organization"></p>
	<p class="form-row form-row-wide address-field update_totals_on_change validate-required woocommerce" id="billing_country_field" data-sort="40">
    <label for="grade" class="">Class <abbr class="required" title="required">*</abbr></label>
	<select name="grade" id="grade" class="country_to_state country_select select2-hidden-accessible" autocomplete="country" tabindex="-1" aria-hidden="true">
		<option value="" aria-hidden="true">Select Class</option>
		<option value="10th">10th</option>
		<option value="11th">11th</option><option value="AL">12th</option>
		<option value="Drop Year">Drop Year</option></select>
		
		<noscript><input type="submit" name="woocommerce_checkout_update_totals" value="" />
		</noscript>
	</p>
	<p class="form-row form-row-wide address-field update_totals_on_change validate-required woocommerce" id="billing_country_field" data-sort="40">
		<label for="course" class="">Course <abbr class="required" title="required">*</abbr></label>
		<select name="course" id="course" class="country_to_state country_select select2-hidden-accessible" autocomplete="country" tabindex="-1" aria-hidden="true">
			<option value="" aria-hidden="true">Select Course</option>
			<option value="Zoom Lectures">Zoom Lectures</option>
			<option value="Test Series">Test Series</option><option value="Offline Support">Offline Support</option>
			</select>
			
			<noscript><input type="submit" name="woocommerce_checkout_update_totals" value="Update country" />
			</noscript>
		</p>
		<p class="form-row form-row-wide address-field update_totals_on_change validate-required woocommerce" id="billing_country_field" data-sort="40">
			<label for="city" class="">Town/City <abbr class="required" title="required">*</abbr></label>
			<select name="city" id="city" class="country_to_state country_select select2-hidden-accessible" autocomplete="country" tabindex="-1" aria-hidden="true">
				<option value="" aria-hidden="true">Select City</option>
				<option value="Palanpur">Palanpur</option>
				<option value="Ajmer">Ajmer</option>
				</select>
				
				<noscript><input type="submit" name="woocommerce_checkout_update_totals" value="Update country" />
				</noscript>
			</p>

							<p class="form-row form-row-first validate-required validate-phone" id="billing_phone_field" data-sort="100">
								<label for="phone" class="">Phone <abbr class="required" title="required">*</abbr></label>
								<input type="tel" class="input-text " name="phone" id="phone" placeholder="" value="" autocomplete="tel"></p>
							<p class="form-row form-row-last validate-required validate-email" id="billing_email_field" data-sort="110">
								<label for="email" class="">Email address <abbr class="required" title="required">*</abbr></label>
								<input type="email" class="input-text " name="email" id="email" placeholder="" value="" autocomplete="email username"></p>
	</div>

	</div>

	
			</div>

			<div class="col-2">
				<div class="woocommerce-shipping-fields">
	</div>
<div class="woocommerce-additional-fields">
	
	
		
			<h3>Additional information</h3>

		
		<div class="woocommerce-additional-fields__field-wrapper">
							<p class="form-row notes" id="order_comments_field" data-sort=""><label for="order_comments" class="">Order notes</label><textarea name="order_comments" class="input-text " id="order_comments" placeholder="Notes about your order, e.g. special notes for delivery." rows="2" cols="5"></textarea></p>					</div>

	
	</div>
			</div>
		</div>

		
			
	
			
			
			<input type="submit" class="button alt" name="woocommerce_checkout_place_order" id="place_order" value="Submit" data-value="Submit">
			
			
	
	
</form>

</div>
				</div>
			</div>
		</div>
		<!-- ROW -->
			    
    <!-- COMMENTS -->
	    <!-- COMMENTS -->

</div>
{% endblock %}

templates/submission_result.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Submission Result {% endblock title %}
{% block content %}
<div class="container">
	<div class="jumbotron my-4">

	   	<h3 class="text-info">{{ attempted_question.question.html|safe }}</h3>

		<p>
		    <strong>Your answer: </strong>
		    {{ attempted_question.selected_choice.html|safe }}
		</p>

		{% if attempted_question.selected_choice.is_correct %}
		<h4 class="text-success">Yayy!! Your answer is correct. High Five! 🙌</h4>
		{% else %}
		<h4 class="text-danger">Your answer is incorrect 😟</h4>
		<p>Correct answer was: {{ attempted_question.question.get_correct_choice.html|safe }}</p>
		{% endif %}

		<a class="btn btn-info" href="{% url 'quiz:play' %}">Show next question</a>
	</div>
</div>

{% endblock content %}

templates/user_home.html
{% extends 'base.html' %}
{% block title %} Let's Learn | Welcome {% endblock title %}
{% block content %}
<div class="container my-4">
    <div class="jumbotron">

	      <h2 class="text-center text-success">Congratulations!! You have successfully logged in.</h2>
	      <h3 class="text-center text-info">Before you play the quiz, here are the rules</h3>

        <div class="row">

            <div class="card border-info mx-4 my-4">
                <div class="card-body">
                    <h4 class="card-title">Rules :</h4>
                    <p class="card-text">
                        <ul style="list-style:decimal;">
                            <li>All questions are multiple choice question.</li>
                            <li><span class="text-danger">Only one choice is correct.</span></li>
                            <li>Every question carry equal marks i.e. <span class="text-danger">4 marks for each question.</span>
                            </li>
                            <li>Every question is displayed only once per user.</li>
                            <li>Try to answer as quickly as you can.</li>
                            <li>If you press refresh or go back to the previous page, there will be a new question for you and the question you were on will be counted as attempted.</li>
                            <li>Questions are displayed randomly for every user.</li>
                            <li>You will be told immediately whether your answer was correct or incorrect once you submit the answer.</li>
                        </ul>
                    </p>
                    <a href="{% url 'quiz:play' %}" class="btn btn-success my-2 ml-4">Let's play</a>
                </div>
                <div class="card-footer text-danger">Rules last modified 08-March-2018</div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}